version: "3.1"

recipe: default.v1  # ✅ Explicitly specify the recipe to remove warnings

assistant_id: "my_rasa_bot"

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true  # ✅ Fixes similarity warning
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
    priority: 2  # ✅ Higher priority for rules
    core_fallback_threshold: 0.3
    core_fallback_action_name: "chat_with_ai"  # ✅ Fallback to AI chat
